@echo off
set GODOT="C:\Users\LEONARDO\Documents\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64_console.exe"
echo Iniciando Servidor...
start "Server" /b %GODOT% --headless -- --server > server_output.txt 2>&1
ping 127.0.0.1 -n 3 > nul
echo Iniciando Cliente 1...
start "Client1" /b %GODOT% --headless -- --client > client1_output.txt 2>&1
echo Iniciando Cliente 2...
start "Client2" /b %GODOT% --headless -- --client > client2_output.txt 2>&1
echo Aguardando sincronizacao...
ping 127.0.0.1 -n 30 > nul
echo Encerrando processos...
taskkill /IM Godot_v4.7.1-stable_win64_console.exe /F
echo Teste concluido!
